name: Check Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  check-pull-request:
    name: Check Pull Request
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test
        env:
          CI: true
