name: Continuous Integration (PROD)
on:
  pull_request:
    branches:
      - master

jobs:
  test-pull-request:
    name: Check Pull Request
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Build
        run: npm run build
